# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Human Augmentation Lab
subtitle: HAL
email: sam@olin.edu
description: > # this means to ignore newlines until "baseurl:"
 The Human Augmentation Lab (HAL) is a research group at Olin College of Engineering directed by Dr. Sam Michalka. Our work aims to understand human attention and memory and to use this knowledge to develop personal technological devices that can respond to our intentions and cognitive states. Combining neuroscience and engineering, we conduct experiments about human behavior and build brain-machine interfaces.
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
baseurl: ""
url: "https://humanaugmentationlab.github.io"
keywords: "brain-machine interface, neuroscience, augmented reality, augmentation, human-machine, brain"

include:
  - .htaccess
  - _pages

sass:
  sass_dir: _sass

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Plugin for search engines
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links
